services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: clinic-postgres
    environment:
      POSTGRES_DB: clinicdb
      POSTGRES_USER: clinicuser
      POSTGRES_PASSWORD: clinicpass
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - clinic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinicuser -d clinicdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: clinic-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clinic.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5051:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - clinic-network
    depends_on:
      - postgres

  # Tomcat Application Server
  tomcat:
    build: .
    container_name: clinic-tomcat
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=clinicdb
      - DB_USER=clinicuser
      - DB_PASSWORD=clinicpass
    volumes:
      - ./target/clinic-jee-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    networks:
      - clinic-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:

networks:
  clinic-network:
    driver: bridge
